// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCelUUUeoNlOrzpbWjzGsMePnCz4L7A_iI',
    appId: '1:241262397269:web:3db2e9b493f9ad50ac91dc',
    messagingSenderId: '241262397269',
    projectId: 'sos-map-12c70',
    authDomain: 'sos-map-12c70.firebaseapp.com',
    storageBucket: 'sos-map-12c70.firebasestorage.app',
    measurementId: 'G-K0SKJWGJG9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDJl9bFU6xC7tNOGU66LpMEaKmJFPaylg',
    appId: '1:241262397269:android:630800a5d4e57460ac91dc',
    messagingSenderId: '241262397269',
    projectId: 'sos-map-12c70',
    storageBucket: 'sos-map-12c70.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7t9-sy9IVxnQDPacPGJWenva1jIa20pw',
    appId: '1:241262397269:ios:629fa1671a679783ac91dc',
    messagingSenderId: '241262397269',
    projectId: 'sos-map-12c70',
    storageBucket: 'sos-map-12c70.firebasestorage.app',
    iosBundleId: 'com.example.sos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7t9-sy9IVxnQDPacPGJWenva1jIa20pw',
    appId: '1:241262397269:ios:629fa1671a679783ac91dc',
    messagingSenderId: '241262397269',
    projectId: 'sos-map-12c70',
    storageBucket: 'sos-map-12c70.firebasestorage.app',
    iosBundleId: 'com.example.sos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCelUUUeoNlOrzpbWjzGsMePnCz4L7A_iI',
    appId: '1:241262397269:web:9403aced2c7f2cb4ac91dc',
    messagingSenderId: '241262397269',
    projectId: 'sos-map-12c70',
    authDomain: 'sos-map-12c70.firebaseapp.com',
    storageBucket: 'sos-map-12c70.firebasestorage.app',
    measurementId: 'G-T43LV6BVGC',
  );
}
